/*
 * Created on Oct 12, 2005
 *
 * To change the template for this generated file go to
 * Window&gt;Preferences&gt;Java&gt;Code Generation&gt;Code and Comments
 */
package mx.com.interware.spira.web.si01;

import mx.com.interware.spira.dto.SI01ResponseDTO;
import mx.com.interware.spira.message.exceptions.TotalMessageException;

import org.apache.log4j.Logger;

public class TestSI01 {
	private static Logger log = Logger.getLogger(TestSI01.class);

	public static void main(String[] args) {
		SI01 servicesSI01 = new SI01Impl();
//		String account = "4218110000247194";
		String account = //"4218110010845888";
		 
//			"4631860000006060";
//			"4218110004766694";
//			"4218110005980088";
//			"4631870000003654";
//			"7603001000016448";
//			"4218110007497404";
//			"4218120000603254";
//			"6046442100000071";
//			"6046442100000071";
//			"4218110011186340";
//			"4218110010843784";
//			"4218110007225326";		
//			"4218110006434978";
//			"4218110010102389";
//			"7603000000008488";
//			"4218110007374280";
//			"4218110010845888";
//			"4218110004820285";
//			"4218110021121634";
//			"6046442100036380";
//			"4631870000003454";
//			"4218110021320210";
//			"4218119000567592";		
//			"4218110004156466";
//			"4218110021108276";
//			"4218119000270718";
//			"4218110021214983";
//			"4218110021763823";
//			"4218119000848810";
//			"4218110020815988";
//			"4631860000014643";
			//"4461380000262071";
			"5295060000006582";
						
		SI01ResponseDTO responseDTO;
		try {
			responseDTO = servicesSI01.getSI01ResponseDTO(account);
			System.out.println("ADDRESS_CITY " + responseDTO.getADDRESS_CITY());
			System.out.println("STATE_ABBRE_ADDLN1 " + responseDTO.getSTATE_ABBRE_ADDLN1());
			System.out.println("CITY_STATE_COMBINE " + responseDTO.getCITY_STATE_COMBINE());
			
			System.out.println("ACCOUNT_CYCLE " + responseDTO.getACCOUNT_CYCLE());
			System.out.println("TRANSFER_STATUS " + responseDTO.getTRANSFER_STATUS());
			System.out.println("TRANSFER_REASON " + responseDTO.getTRANSFER_REASON());
			System.out.println("TRANSFER_DATE " + responseDTO.getTRANSFER_DATE());
			System.out.println("LOST_ACCT_STATUS " + responseDTO.getLOST_ACCT_STATUS());
			System.out.println("ACCT_DELETE_STATUS " + responseDTO.getACCT_DELETE_STATUS());
			System.out.println("CUR_ACCT_COL_STAT " + responseDTO.getCUR_ACCT_COL_STAT());
			System.out.println("OLD_CYC_AFT_CHGOF " + responseDTO.getOLD_CYC_AFT_CHGOF());
			System.out.println("REISSUE_DAY " + responseDTO.getREISSUE_DAY());
			System.out.println("TYPE_CODE " + responseDTO.getTYPE_CODE());
			System.out.println("LAST_CRD_RATE_CHG " + responseDTO.getLAST_CRD_RATE_CHG());
			System.out.println("CREDIT_RATING " + responseDTO.getCREDIT_RATING());
			System.out.println("AGENT " + responseDTO.getAGENT());
			System.out.println("ISSUE_BANK " + responseDTO.getISSUE_BANK());
			System.out.println("BRANCH " + responseDTO.getBRANCH());
			System.out.println("CREDIT_SCORE " + responseDTO.getCREDIT_SCORE());
			System.out.println("LAST_DT_SC_CHG " + responseDTO.getLAST_DT_SC_CHG());
			System.out.println("OFFCR_CHANGE_SCR " + responseDTO.getOFFCR_CHANGE_SCR());
			System.out.println("ORIG_CREDIT_SCORE " + responseDTO.getORIG_CREDIT_SCORE());
			System.out.println("STATUS " + responseDTO.getSTATUS());
			System.out.println("AUTO_MAN_CBR " + responseDTO.getAUTO_MAN_CBR());
			System.out.println("MANUAL_OVRRIDE_CBR " + responseDTO.getMANUAL_OVRRIDE_CBR());
			System.out.println("OVR_CVR_BREXCEP " + responseDTO.getOVR_CVR_BREXCEP());
			System.out.println("TST_CBR_ISS_CREXC " + responseDTO.getTST_CBR_ISS_CREXC());
			System.out.println("ACCT_TYPE_EXCEP " + responseDTO.getACCT_TYPE_EXCEP());
			System.out.println("AUTH_OS_EXCEP " + responseDTO.getAUTH_OS_EXCEP());
			System.out.println("ACT_TODAY_EXCEP " + responseDTO.getACT_TODAY_EXCEP());
			System.out.println("BEHAVORIAL_SCORE " + responseDTO.getBEHAVORIAL_SCORE());
			System.out.println("OFFICER " + responseDTO.getOFFICER());
			System.out.println("OUTSTANDING_AUTHS " + responseDTO.getOUTSTANDING_AUTHS());
			System.out.println("OS_AUTH_AMT " + responseDTO.getOS_AUTH_AMT());
			System.out.println("CURRENTLY_OVRLIMIT " + responseDTO.getCURRENTLY_OVRLIMIT());
			System.out.println("NUM_OF_STATEMENTS " + responseDTO.getNUM_OF_STATEMENTS());
			System.out.println("NUM_OF_TM_CD_BAL " + responseDTO.getNUM_OF_TM_CD_BAL());
			System.out.println("DAYS_IN_CRED_BAL " + responseDTO.getDAYS_IN_CRED_BAL());
			System.out.println("DAYS_OVERLIMIT " + responseDTO.getDAYS_OVERLIMIT());
			System.out.println("DAYS_PAST_DUE " + responseDTO.getDAYS_PAST_DUE());
			System.out.println("NUM_OL_NOTICES " + responseDTO.getNUM_OL_NOTICES());
			System.out.println("OL_SINCE_OPEN " + responseDTO.getOL_SINCE_OPEN());
			System.out.println("DATE_LST_OL_SNT " + responseDTO.getDATE_LST_OL_SNT());
			System.out.println("TIMES_PD_CYCLE " + responseDTO.getTIMES_PD_CYCLE());
			System.out.println("PD_NOTC_1_SENT " + responseDTO.getPD_NOTC_1_SENT());
			System.out.println("PD_NOTC_2_SENT " + responseDTO.getPD_NOTC_2_SENT());
			System.out.println("COLL_CARD_SENT " + responseDTO.getCOLL_CARD_SENT());
			System.out.println("PD_NOTC_3_SENT " + responseDTO.getPD_NOTC_3_SENT());
			System.out.println("OVERLIM_LET_1 " + responseDTO.getOVERLIM_LET_1());
			System.out.println("OVERLIM_LET_2 " + responseDTO.getOVERLIM_LET_2());
			System.out.println("NON_ACC_STATUS " + responseDTO.getNON_ACC_STATUS());
			System.out.println("CRED_LIM_INC_LET " + responseDTO.getCRED_LIM_INC_LET());
			System.out.println("ACCT_IN_DISPUTE " + responseDTO.getACCT_IN_DISPUTE());
			System.out.println("LAST_DISPUTE_DATE " + responseDTO.getLAST_DISPUTE_DATE());
			System.out.println("OFCR_APPR_LST_DIS " + responseDTO.getOFCR_APPR_LST_DIS());
			System.out.println("AMT_CUR_IN_DISP " + responseDTO.getAMT_CUR_IN_DISP());
			System.out.println("LAST_DISPUTE_SETLD " + responseDTO.getLAST_DISPUTE_SETLD());
			System.out.println("NUM_TIMES_DISPUTE " + responseDTO.getNUM_TIMES_DISPUTE());
			System.out.println("RESTRICTED_CARD_LS " + responseDTO.getRESTRICTED_CARD_LS());
			System.out.println("REASON_ON_RCL " + responseDTO.getREASON_ON_RCL());
			System.out.println("REG_CODE_FOR_RCL " + responseDTO.getREG_CODE_FOR_RCL());
			System.out.println("DATE_LAST_ON_RCL " + responseDTO.getDATE_LAST_ON_RCL());
			System.out.println("PURGE_DATE_FOR_RCL " + responseDTO.getPURGE_DATE_FOR_RCL());
			System.out.println("ACCT_IN_CRB_STAT " + responseDTO.getACCT_IN_CRB_STAT());
			System.out.println("CRB_REASON " + responseDTO.getCRB_REASON());
			System.out.println("CRB_REGION_CODE " + responseDTO.getCRB_REGION_CODE());
			System.out.println("PURGE_DATE_FOR_CRB " + responseDTO.getPURGE_DATE_FOR_CRB());
			System.out.println("DAT_LAST_ON_CRB " + responseDTO.getDAT_LAST_ON_CRB());
			System.out.println("DONT_PRINT_PAST_DU " + responseDTO.getDONT_PRINT_PAST_DU());
			System.out.println("DONT_PRINT_OVERLMT " + responseDTO.getDONT_PRINT_OVERLMT());
			System.out.println("DONT_PRNT_PAST_MSG " + responseDTO.getDONT_PRNT_PAST_MSG());
			System.out.println("DONT_PRNT_OVLM_MSG " + responseDTO.getDONT_PRNT_OVLM_MSG());
			System.out.println("DONT_PRNT_STATEMNT " + responseDTO.getDONT_PRNT_STATEMNT());
			System.out.println("IMMUNE_AT_CYCLE " + responseDTO.getIMMUNE_AT_CYCLE());
			System.out.println("FC_PREC_4_DEC " + responseDTO.getFC_PREC_4_DEC());
			System.out.println("STRIPE_WAS_READ " + responseDTO.getSTRIPE_WAS_READ());
			System.out.println("CHG_TAX_THIS_CYCLE " + responseDTO.getCHG_TAX_THIS_CYCLE());
			System.out.println("DATE_NOTC_PRT_CHG " + responseDTO.getDATE_NOTC_PRT_CHG());
			System.out.println("OFCR_APP_NOTC_CHG " + responseDTO.getOFCR_APP_NOTC_CHG());
			System.out.println("INS_RATE_CODE " + responseDTO.getINS_RATE_CODE());
			System.out.println("MONTH_INS_DUE " + responseDTO.getMONTH_INS_DUE());
			System.out.println("TIMES_INS_CAL_OPN " + responseDTO.getTIMES_INS_CAL_OPN());
			System.out.println("CH_BIRTH_DATE " + responseDTO.getCH_BIRTH_DATE());
			System.out.println("USER_CODE_1 " + responseDTO.getUSER_CODE_1());
			System.out.println("USER_CODE_2_POS0 " + responseDTO.getUSER_CODE_2_POS0());
			System.out.println("USER_CODE_2_POS1 " + responseDTO.getUSER_CODE_2_POS1());
			System.out.println("USER_CODE_2_POS2 " + responseDTO.getUSER_CODE_2_POS2());
			System.out.println("USER_CODE_2_POS3 " + responseDTO.getUSER_CODE_2_POS3());
			System.out.println("USER_CODE_3 " + responseDTO.getUSER_CODE_3());
			System.out.println("USER_ACCT_1 " + responseDTO.getUSER_ACCT_1());
			System.out.println("USER_ACCT_2 " + responseDTO.getUSER_ACCT_2());
			System.out.println("USER_ACCT_3 " + responseDTO.getUSER_ACCT_3());
			System.out.println("OTH_ACCT_NUMBER " + responseDTO.getOTH_ACCT_NUMBER());
			System.out.println("DDA_ACCNT_NUMBER " + responseDTO.getDDA_ACCNT_NUMBER());
			System.out.println("SAV_ACCT_NUMBER " + responseDTO.getSAV_ACCT_NUMBER());
			System.out.println("INS_LOAN_ACCT_NBR " + responseDTO.getINS_LOAN_ACCT_NBR());
			System.out.println("TRNACCT_NR_OLD_NW " + responseDTO.getTRNACCT_NR_OLD_NW());
			System.out.println("CARDS_OUTSTANDING " + responseDTO.getCARDS_OUTSTANDING());
			System.out.println("CARDS_TOBE_REISSUE " + responseDTO.getCARDS_TOBE_REISSUE());
			System.out.println("EXP_DT_CUR_CARD " + responseDTO.getEXP_DT_CUR_CARD());
			System.out.println("TRANSIT_ROUTING_NB " + responseDTO.getTRANSIT_ROUTING_NB());
			System.out.println("DOCUTEL_PIN_NUMBER " + responseDTO.getDOCUTEL_PIN_NUMBER());
			System.out.println("DIEBOLD_OFFSET_PIN " + responseDTO.getDIEBOLD_OFFSET_PIN());
			System.out.println("DIEBOLD_ENTRY_NBR " + responseDTO.getDIEBOLD_ENTRY_NBR());
			System.out.println("ISD_FILL_T " + responseDTO.getISD_FILL_T());
			System.out.println("DIEBOLD_WITHDR_LMT " + responseDTO.getDIEBOLD_WITHDR_LMT());
			System.out.println("BUSINESS_LOGO_FLD " + responseDTO.getBUSINESS_LOGO_FLD());
			System.out.println("CORP_ACCT_NUMBER " + responseDTO.getCORP_ACCT_NUMBER());
			System.out.println("ISD_FILL_0 " + responseDTO.getISD_FILL_0());
			System.out.println("OVERDRAFT_COV_FLAG " + responseDTO.getOVERDRAFT_COV_FLAG());
			System.out.println("DUAL_VISA_MAST_PL " + responseDTO.getDUAL_VISA_MAST_PL());
			System.out.println("CARD_USE_REPORTED " + responseDTO.getCARD_USE_REPORTED());
			System.out.println("DATE_CARD_1ST_USED " + responseDTO.getDATE_CARD_1ST_USED());
			System.out.println("PSTDU_MANUALY_CHGD " + responseDTO.getPSTDU_MANUALY_CHGD());
			System.out.println("TIMES_PSTDUE_CHGMN " + responseDTO.getTIMES_PSTDUE_CHGMN());
			System.out.println("LST_PASTDUE_MAN_CH " + responseDTO.getLST_PASTDUE_MAN_CH());
			System.out.println("LAST_PASTDUE_NOTIC " + responseDTO.getLAST_PASTDUE_NOTIC());
			System.out.println("OFCR_APP_PT_DU_CH " + responseDTO.getOFCR_APP_PT_DU_CH());
			System.out.println("LAST_CRED_RPT_CHCK " + responseDTO.getLAST_CRED_RPT_CHCK());
			System.out.println("DATE_ACCT_OPENNED " + responseDTO.getDATE_ACCT_OPENNED());
			System.out.println("LAST_STATEMENT_DT " + responseDTO.getLAST_STATEMENT_DT());
			System.out.println("LAST_MAINT_DATE " + responseDTO.getLAST_MAINT_DATE());
			System.out.println("PRIR_LAST_MAINT_DT " + responseDTO.getPRIR_LAST_MAINT_DT());
			System.out.println("LAST_MAG_MAINT " + responseDTO.getLAST_MAG_MAINT());
			System.out.println("LAST_CRED_ON_ACCT " + responseDTO.getLAST_CRED_ON_ACCT());
			System.out.println("LAST_PAYMENT_DATE " + responseDTO.getLAST_PAYMENT_DATE());
			System.out.println("LAST_PAYMENT_AMT " + responseDTO.getLAST_PAYMENT_AMT());
			System.out.println("DATE_LAST_PURCHASE " + responseDTO.getDATE_LAST_PURCHASE());
			System.out.println("DATE_LAST_CASH_ADV " + responseDTO.getDATE_LAST_CASH_ADV());
			System.out.println("DATE_LAST_PAST_DUE " + responseDTO.getDATE_LAST_PAST_DUE());
			System.out.println("DATE_LAST_LATE_CHG " + responseDTO.getDATE_LAST_LATE_CHG());
			System.out.println("LAST_TRANSACT_DATE " + responseDTO.getLAST_TRANSACT_DATE());
			System.out.println("ANY_TYPE_LAST_ACTV " + responseDTO.getANY_TYPE_LAST_ACTV());
			System.out.println("DATE_OF_LAST_LETTR " + responseDTO.getDATE_OF_LAST_LETTR());
			System.out.println("DATE_PAYMENT_DUE " + responseDTO.getDATE_PAYMENT_DUE());
			System.out.println("PIN_REQUEST_FLAG " + responseDTO.getPIN_REQUEST_FLAG());
			System.out.println("DATE_OF_PIN_REQUEST " + responseDTO.getDATE_OF_PIN_REQUEST());
			System.out.println("DATE_SENT_CREDBURU " + responseDTO.getDATE_SENT_CREDBURU());
			System.out.println("SPOUSE_RESP_FR_ACT " + responseDTO.getSPOUSE_RESP_FR_ACT());
			System.out.println("SPOUSE_RESP_CODE " + responseDTO.getSPOUSE_RESP_CODE());
			System.out.println("ADDR_CHG_S_BUREAU " + responseDTO.getADDR_CHG_S_BUREAU());
			System.out.println("NAME_LNE1_CHANGE " + responseDTO.getNAME_LNE1_CHANGE());
			System.out.println("NAME_LNE2_CHANGE " + responseDTO.getNAME_LNE2_CHANGE());
			System.out.println("NAME_LINE2_ADDED " + responseDTO.getNAME_LINE2_ADDED());
			System.out.println("CREDITBUREA_REPORT " + responseDTO.getCREDITBUREA_REPORT());
			System.out.println("CARD_REQ_TODAY " + responseDTO.getCARD_REQ_TODAY());
			System.out.println("CARD_REQ_DEL_TOD " + responseDTO.getCARD_REQ_DEL_TOD());
			System.out.println("DEL_TRADE_FM_BUREA " + responseDTO.getDEL_TRADE_FM_BUREA());
			System.out.println("ORIG_CREDIT_LIMIT " + responseDTO.getORIG_CREDIT_LIMIT());
			System.out.println("NBR_TIMES_LIM_CHGD " + responseDTO.getNBR_TIMES_LIM_CHGD());
			System.out.println("OFCR_APPV_LIMT_CHG " + responseDTO.getOFCR_APPV_LIMT_CHG());
			System.out.println("LAST_LIMIT_INC_DEC " + responseDTO.getLAST_LIMIT_INC_DEC());
			System.out.println("DATE_LAST_LIM_CHG " + responseDTO.getDATE_LAST_LIM_CHG());
			System.out.println("TYPE_OF_LIMIT_CHG " + responseDTO.getTYPE_OF_LIMIT_CHG());
			System.out.println("FIXED_PAYMENT_AMT " + responseDTO.getFIXED_PAYMENT_AMT());
			System.out.println("DATE_FIXED_PAY_STR " + responseDTO.getDATE_FIXED_PAY_STR());
			System.out.println("DATE_FIX_PAYAMT_CH " + responseDTO.getDATE_FIX_PAYAMT_CH());
			System.out.println("OFCR_APPR_FIXED_P " + responseDTO.getOFCR_APPR_FIXED_P());
			System.out.println("HIGH_BAL_ON_ACCT " + responseDTO.getHIGH_BAL_ON_ACCT());
			System.out.println("DATE_HIGH_BAL_REAC " + responseDTO.getDATE_HIGH_BAL_REAC());
			System.out.println("FIN_CHARGE_CYCLE " + responseDTO.getFIN_CHARGE_CYCLE());
			System.out.println("PAST_DUE_LETTER_1 " + responseDTO.getPAST_DUE_LETTER_1());
			System.out.println("PAST_DUE_LETTER_2 " + responseDTO.getPAST_DUE_LETTER_2());
			System.out.println("PAST_DUE_LETTER_3 " + responseDTO.getPAST_DUE_LETTER_3());
			System.out.println("PAST_DUE_LETTER_4 " + responseDTO.getPAST_DUE_LETTER_4());
			System.out.println("PAST_DUE_LETTER_5 " + responseDTO.getPAST_DUE_LETTER_5());
			System.out.println("PAST_DUE_LETTER_6 " + responseDTO.getPAST_DUE_LETTER_6());
			System.out.println("PAST_DUE_LETTER_7 " + responseDTO.getPAST_DUE_LETTER_7());
			System.out.println("STATE_CD_FOR_ACCT " + responseDTO.getSTATE_CD_FOR_ACCT());
			System.out.println("SKIP_PAYMENT_STATE " + responseDTO.getSKIP_PAYMENT_STATE());
			System.out.println("TYPE_AUTO_DEDUCTIO " + responseDTO.getTYPE_AUTO_DEDUCTIO());
			System.out.println("METHOD_FOR_AUTO_DE " + responseDTO.getMETHOD_FOR_AUTO_DE());
			System.out.println("ACT_REISSUE_RATING " + responseDTO.getACT_REISSUE_RATING());
			System.out.println("EXPDATE_BEF_REISSU " + responseDTO.getEXPDATE_BEF_REISSU());
			System.out.println("ENCODE_ALL_ACCTS " + responseDTO.getENCODE_ALL_ACCTS());
			System.out.println("STR_CRD_ALPHA_PIN " + responseDTO.getSTR_CRD_ALPHA_PIN());
			System.out.println("CHECK_OK_CARD " + responseDTO.getCHECK_OK_CARD());
			System.out.println("CHG_IN_TERMS_COMP " + responseDTO.getCHG_IN_TERMS_COMP());
			System.out.println("REISSU_CRD_PRINTED " + responseDTO.getREISSU_CRD_PRINTED());
			System.out.println("DELETE_PROC_COMP " + responseDTO.getDELETE_PROC_COMP());
			System.out.println("CHARGEOFF_PROC_COM " + responseDTO.getCHARGEOFF_PROC_COM());
			System.out.println("TRANSFER_PROC_COMP " + responseDTO.getTRANSFER_PROC_COMP());
			System.out.println("ACCT_ACTIVE_TODAY " + responseDTO.getACCT_ACTIVE_TODAY());
			System.out.println("ACCT_ACT_THIS_MONT " + responseDTO.getACCT_ACT_THIS_MONT());
			System.out.println("ACCT_ACTIVE_T_YEAR " + responseDTO.getACCT_ACTIVE_T_YEAR());
			System.out.println("ACCT_ACT_PRIR_YEAR " + responseDTO.getACCT_ACT_PRIR_YEAR());
			System.out.println("ACCT_ACT_SINCE_OPE " + responseDTO.getACCT_ACT_SINCE_OPE());
			System.out.println("DEB_ACTIVITY_TODAY " + responseDTO.getDEB_ACTIVITY_TODAY());
			System.out.println("CRED_ACTVITY_TODAY " + responseDTO.getCRED_ACTVITY_TODAY());
			System.out.println("SUPP_AIR_INS_ACT_M " + responseDTO.getSUPP_AIR_INS_ACT_M());
			System.out.println("SALES_DRFT_TH_CYCL " + responseDTO.getSALES_DRFT_TH_CYCL());
			System.out.println("CASH_ADV_THIS_CYC " + responseDTO.getCASH_ADV_THIS_CYC());
			System.out.println("CREDIT_THIS_CYCLE " + responseDTO.getCREDIT_THIS_CYCLE());
			System.out.println("PAYMENT_THIS_CYCLE " + responseDTO.getPAYMENT_THIS_CYCLE());
			System.out.println("SALES_DRAFT_REV_CY " + responseDTO.getSALES_DRAFT_REV_CY());
			System.out.println("CASHADV_REV_TH_CYC " + responseDTO.getCASHADV_REV_TH_CYC());
			System.out.println("CRED_REV_THIS_CYCL " + responseDTO.getCRED_REV_THIS_CYCL());
			System.out.println("PAYMENT_REV_T_CYCL " + responseDTO.getPAYMENT_REV_T_CYCL());
			System.out.println("PREV_STATE_BAL " + responseDTO.getPREV_STATE_BAL());
			System.out.println("PREV_PURCHASE_BAL " + responseDTO.getPREV_PURCHASE_BAL());
			System.out.println("PREV_CASHADV_BAL " + responseDTO.getPREV_CASHADV_BAL());
			System.out.println("PREVPUR_FINCHG_OUT " + responseDTO.getPREVPUR_FINCHG_OUT());
			System.out.println("PREV_CASHADV_FINCH " + responseDTO.getPREV_CASHADV_FINCH());
			System.out.println("PREV_MISC_OUTSTAND " + responseDTO.getPREV_MISC_OUTSTAND());
			System.out.println("PREV_STATE_LATECHG " + responseDTO.getPREV_STATE_LATECHG());
			System.out.println("PREV_STATE_INS_CHG " + responseDTO.getPREV_STATE_INS_CHG());
			System.out.println("PREV_STATE_ACT_DUE " + responseDTO.getPREV_STATE_ACT_DUE());
			System.out.println("DATE_LAST_ANNFEE_C " + responseDTO.getDATE_LAST_ANNFEE_C());
			System.out.println("AMT_LAST_ANNUAL_FE " + responseDTO.getAMT_LAST_ANNUAL_FE());
			System.out.println("ANNUAL_FEE_FLAG " + responseDTO.getANNUAL_FEE_FLAG());
			System.out.println("ANNUAL_FEE_RATECDE " + responseDTO.getANNUAL_FEE_RATECDE());
			System.out.println("CHARGEOFF_STATUS " + responseDTO.getCHARGEOFF_STATUS());
			System.out.println("DATE_CHARGE_OFF " + responseDTO.getDATE_CHARGE_OFF());
			System.out.println("BAL_CHARGED_OFF " + responseDTO.getBAL_CHARGED_OFF());
			System.out.println("CHARGEOFF_REASON " + responseDTO.getCHARGEOFF_REASON());
			
			System.out.println("**RATECD_UND_BP1 " + responseDTO.getRATECD_UND_BP1());
			System.out.println("**RATECD_OVR1_U2 " + responseDTO.getRATECD_OVR1_U2());
			System.out.println("**RATECD_OVR_BP2 " + responseDTO.getRATECD_OVR_BP2());
			
			System.out.println("3_PURCHASE_RT_CDS " + responseDTO.getTHREE_PURCHASE_RT_CDS());
			
			System.out.println("**RATE_CA_CD_UND_BP1 " + responseDTO.getRATECD_CA_UND1());
			System.out.println("**RATECD_OVR1_U2 " + responseDTO.getRATECD_CA_OV1U2());
			System.out.println("**RATECD_OVR_BP2 " + responseDTO.getRATECD_CA_OVR2());
			
			System.out.println("3_CASHADV_RATECODE " + responseDTO.getTHREE_CASHADV_RATECODE());
			System.out.println("RATECODE_CSHADV_FE " + responseDTO.getRATECODE_CSHADV_FE());
			System.out.println("RATECODE_MINPAYMNT " + responseDTO.getRATECODE_MINPAYMNT());
			System.out.println("RATECODE_LATECHG_F " + responseDTO.getRATECODE_LATECHG_F());
			System.out.println("HOLD_PLASTIC " + responseDTO.getHOLD_PLASTIC());
			System.out.println("ZIP4_NOT_CONVERT " + responseDTO.getZIP4_NOT_CONVERT());
			System.out.println("ZIP4_IS_VALID " + responseDTO.getZIP4_IS_VALID());
			System.out.println("ONL_ADDRCHG_UPD_OV " + responseDTO.getONL_ADDRCHG_UPD_OV());
			System.out.println("UTH_USER1_HASCARD " + responseDTO.getUTH_USER1_HASCARD());
			System.out.println("AUTH_USER2_HASCARD " + responseDTO.getAUTH_USER2_HASCARD());
			System.out.println("AUTH_USER3_HASCARD " + responseDTO.getAUTH_USER3_HASCARD());
			System.out.println("DATE_LAT_NMADDR_MN " + responseDTO.getDATE_LAT_NMADDR_MN());
			System.out.println("SSN_FOR_NAME_LINE1 " + responseDTO.getSSN_FOR_NAME_LINE1());
			System.out.println("HOME_PHONE_NUMBER " + responseDTO.getHOME_PHONE_NUMBER());
			System.out.println("BUSINESS_PHONE_NUMBER " + responseDTO.getBUSINESS_PHONE_NUMBER());
			System.out.println("SPOUSE_NAME " + responseDTO.getSPOUSE_NAME());
			System.out.println("PLACE_OF_EMPLOYMEN " + responseDTO.getPLACE_OF_EMPLOYMEN());
			System.out.println("NAME_LINE1_PRIM_AP " + responseDTO.getNAME_LINE1_PRIM_AP());
			System.out.println("NAME_LINE2_COAPPL " + responseDTO.getNAME_LINE2_COAPPL());
			System.out.println("ADDRESS_LINE_1 " + responseDTO.getADDRESS_LINE_1());
			System.out.println("ADDRESS_LINE_2 " + responseDTO.getADDRESS_LINE_2());
			
			/****Aqui van dos campos****/
			
			
			System.out.println("AUTH_USER_NAME1 " + responseDTO.getAUTH_USER_NAME1());
			System.out.println("AUTH_USER_NAME2 " + responseDTO.getAUTH_USER_NAME2());
			System.out.println("AUTH_USER_NAME3 " + responseDTO.getAUTH_USER_NAME3());
			System.out.println("STATEMENT_HOLD_CDE " + responseDTO.getSTATEMENT_HOLD_CDE());
			System.out.println("ZIPCODE_CARDHOLDER " + responseDTO.getZIPCODE_CARDHOLDER());
			System.out.println("LAST_AUTO_PASTDUE " + responseDTO.getLAST_AUTO_PASTDUE());
			System.out.println("TIMES_AUTO_PASTDUE " + responseDTO.getTIMES_AUTO_PASTDUE());
			System.out.println("AGENT_BANK_NAME " + responseDTO.getAGENT_BANK_NAME());
			System.out.println("EXT_TRNACCT_NR_OLD " + responseDTO.getEXT_TRNACCT_NR_OLD());
			System.out.println("SHORT_NAME " + responseDTO.getSHORT_NAME());
			System.out.println("RATE_CODE_CH_COMPL " + responseDTO.getRATE_CODE_CH_COMPL());
			System.out.println("CAN_CHG_MBRSHIP_FE " + responseDTO.getCAN_CHG_MBRSHIP_FE());
			System.out.println("CAN_CHG_OVRLMT_FEE " + responseDTO.getCAN_CHG_OVRLMT_FEE());
			System.out.println("ACCT_HAS_VISA_PHONE " + responseDTO.getACCT_HAS_VISA_PHONE());
			System.out.println("BILL_FEDX_CARD_DE " + responseDTO.getBILL_FEDX_CARD_DE());
			System.out.println("CARD_ACTIVATION_ST " + responseDTO.getCARD_ACTIVATION_ST());
			System.out.println("INDICATE_PURCH_IHB " + responseDTO.getINDICATE_PURCH_IHB());
			System.out.println("INDICATE_CASH_IHB " + responseDTO.getINDICATE_CASH_IHB());
			System.out.println("PAST_DUE_NOTICE_1 " + responseDTO.getPAST_DUE_NOTICE_1());
			System.out.println("PAST_DUE_NOTICE_2 " + responseDTO.getPAST_DUE_NOTICE_2());
			System.out.println("AUTO_LTR_1 " + responseDTO.getAUTO_LTR_1());
			System.out.println("AUTO_LTR_2 " + responseDTO.getAUTO_LTR_2());
			System.out.println("AUTO_LTR_3 " + responseDTO.getAUTO_LTR_3());
			System.out.println("AUTO_LTR_4 " + responseDTO.getAUTO_LTR_4());
			System.out.println("ACCT_DNLD_FROM_SSI " + responseDTO.getACCT_DNLD_FROM_SSI());
			System.out.println("ACCT_NEW_TO_SSI_RM " + responseDTO.getACCT_NEW_TO_SSI_RM());
			System.out.println("ACE_STATUS_BYTE " + responseDTO.getACE_STATUS_BYTE());
			System.out.println("QTRLY_PMT_MO_COUNT " + responseDTO.getQTRLY_PMT_MO_COUNT());
			System.out.println("DEF_PMT_SCHD_CNTDN " + responseDTO.getDEF_PMT_SCHD_CNTDN());
			System.out.println("DEF_PMT_SCHD_REFRE " + responseDTO.getDEF_PMT_SCHD_REFRE());
			System.out.println("NWB_STATUS " + responseDTO.getNWB_STATUS());
			System.out.println("NWB_ACCT_LISTED " + responseDTO.getNWB_ACCT_LISTED());
			System.out.println("JVTYPE " + responseDTO.getJVTYPE());
			System.out.println("LONG_NAME " + responseDTO.getLONG_NAME());
			System.out.println("TAXID " + responseDTO.getTAXID());
			System.out.println("BUSN_EXT " + responseDTO.getBUSN_EXT());
			System.out.println("PREV_POINT_BAL " + responseDTO.getPREV_POINT_BAL());
			System.out.println("ACCUM_POINTS " + responseDTO.getACCUM_POINTS());
			System.out.println("POINTS_USED " + responseDTO.getPOINTS_USED());
			System.out.println("EXPIRED_POINTS " + responseDTO.getEXPIRED_POINTS());
			System.out.println("CURR_POINT_BAL " + responseDTO.getCURR_POINT_BAL());
			System.out.println("BONUS_POINT_CDATE " + responseDTO.getBONUS_POINT_CDATE());
			System.out.println("ISD_FILL3 " + responseDTO.getISD_FILL3());
			System.out.println("FRAUD_MESSAGE_IND " + responseDTO.getFRAUD_MESSAGE_IND());
			System.out.println("COMB_DET_STATEMENT " + responseDTO.getCOMB_DET_STATEMENT());
			System.out.println("COMB_MASTER_STATEM " + responseDTO.getCOMB_MASTER_STATEM());
			System.out.println("SYS_GENER_PIN " + responseDTO.getSYS_GENER_PIN());
			System.out.println("CUST_SELECTED_PIN " + responseDTO.getCUST_SELECTED_PIN());
			System.out.println("BANK_53 " + responseDTO.getBANK_53());
			System.out.println("BANK_SPECIFIC_IND " + responseDTO.getBANK_SPECIFIC_IND());
			System.out.println("BANK_SPEC2_IND " + responseDTO.getBANK_SPEC2_IND());
			System.out.println("FREE_TEXT_STATUS " + responseDTO.getFREE_TEXT_STATUS());
			System.out.println("EXT_SEG_1_ON_FILE " + responseDTO.getEXT_SEG_1_ON_FILE());
			System.out.println("STATE_PROD_THIS_CY " + responseDTO.getSTATE_PROD_THIS_CY());
			System.out.println("ZERO_BALANCE_YESTE " + responseDTO.getZERO_BALANCE_YESTE());
			System.out.println("AFFIN_DUES_CG_PREV " + responseDTO.getAFFIN_DUES_CG_PREV());
			System.out.println("AFFIN_DUES_FIRST_C " + responseDTO.getAFFIN_DUES_FIRST_C());
			System.out.println("NEW_ACCT_1ST_BBAL " + responseDTO.getNEW_ACCT_1ST_BBAL());
			System.out.println("RET_CHECK_THIS_CYC " + responseDTO.getRET_CHECK_THIS_CYC());
			System.out.println("SENT_TO_MC_TRAV " + responseDTO.getSENT_TO_MC_TRAV());
			System.out.println("ISD_FILL_8 " + responseDTO.getISD_FILL_8());
			System.out.println("AUTH_NCNB_SEC_ON " + responseDTO.getAUTH_NCNB_SEC_ON());
			System.out.println("AUTH_NCNB_SEC_COMP " + responseDTO.getAUTH_NCNB_SEC_COMP());
			System.out.println("ACCT_PENDING_XFR " + responseDTO.getACCT_PENDING_XFR());
			System.out.println("CHANGE_IN_TERM_DT " + responseDTO.getCHANGE_IN_TERM_DT());
			System.out.println("ISD_FILL4 " + responseDTO.getISD_FILL4());
			System.out.println("FRAUD_COUNTERFEIT " + responseDTO.getFRAUD_COUNTERFEIT());
			System.out.println("ISD_FILL5 " + responseDTO.getISD_FILL5());
			System.out.println("PD_FULL_BEF_PAYDUE " + responseDTO.getPD_FULL_BEF_PAYDUE());
			System.out.println("OVERLIMIT_CHRG_COM " + responseDTO.getOVERLIMIT_CHRG_COM());
			System.out.println("ATM_XFER_TODAY_ACC " + responseDTO.getATM_XFER_TODAY_ACC());
			System.out.println("DEBIT_CRDLIM_UPD_T " + responseDTO.getDEBIT_CRDLIM_UPD_T());
			System.out.println("LETTER_REQ_TODAY " + responseDTO.getLETTER_REQ_TODAY());
			System.out.println("LETTER_REQ_DEL_TOD " + responseDTO.getLETTER_REQ_DEL_TOD());
			System.out.println("ACCT_REISSUED_TH_M " + responseDTO.getACCT_REISSUED_TH_M());
			System.out.println("AUTO_LIM_INCR_TH_M " + responseDTO.getAUTO_LIM_INCR_TH_M());
			System.out.println("CO_STMT_FLAG " + responseDTO.getCO_STMT_FLAG());
			
			/****Aqui va un campo****/
			
			
			
			System.out.println("ISD_FILL6 " + responseDTO.getISD_FILL6());
			System.out.println("DATE_TO_CHG_ANN_FE " + responseDTO.getDATE_TO_CHG_ANN_FE());
			System.out.println("ISD_FILL7 " + responseDTO.getISD_FILL7());
			System.out.println("BANK_NUMBER " + responseDTO.getBANK_NUMBER());
			System.out.println("CELL_PHONE " + responseDTO.getCELL_PHONE());
			System.out.println("CURP_ID " + responseDTO.getCURP_ID());
			System.out.println("GUARANTOR1 " + responseDTO.getGUARANTOR1());
			System.out.println("RFC_GUARANTOR1 " + responseDTO.getRFC_GUARANTOR1());
			System.out.println("GUARANTOR2 " + responseDTO.getGUARANTOR2());
			System.out.println("RFC_GUARANTOR2 " + responseDTO.getRFC_GUARANTOR2());
			System.out.println("GUARANTOR3 " + responseDTO.getGUARANTOR3());
			System.out.println("RFC_GUARANTOR3 " + responseDTO.getRFC_GUARANTOR3());
			System.out.println("EMBOSS_NAME " + responseDTO.getEMBOSS_NAME());
			System.out.println("PERSONAL_RFC " + responseDTO.getPERSONAL_RFC());
			System.out.println("EMAIL " + responseDTO.getEMAIL());
			System.out.println("MISC_USER1 " + responseDTO.getMISC_USER1());
			System.out.println("IDS_FILL8 " + responseDTO.getIDS_FILL8());

			System.out.println("INS_RATE_CODE: " + responseDTO.getINS_RATE_CODE());
			System.out.println("MONTH-INS-DUE: " + responseDTO.getMONTH_INS_DUE());
			
			
		} catch (TotalMessageException e) {
			e.printStackTrace();
		}
	}
}
