//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.10.10 at 12:09:56 PM CDT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://mx/com/invex/msi/webservice", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package mx.com.invex.msi.webservice;
