//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.09.26 at 10:35:55 AM CDT 
//


package com.blog.samples.webservices.seguridadservice;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.blog.samples.webservices.seguridadservice package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.blog.samples.webservices.seguridadservice
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link AutentificarRequest }
     * 
     */
    public AutentificarRequest createAutentificarRequest() {
        return new AutentificarRequest();
    }

    /**
     * Create an instance of {@link CerrarSessionResponse }
     * 
     */
    public CerrarSessionResponse createCerrarSessionResponse() {
        return new CerrarSessionResponse();
    }

    /**
     * Create an instance of {@link AutentificarWebRequest }
     * 
     */
    public AutentificarWebRequest createAutentificarWebRequest() {
        return new AutentificarWebRequest();
    }

    /**
     * Create an instance of {@link CerrarSessionRequest }
     * 
     */
    public CerrarSessionRequest createCerrarSessionRequest() {
        return new CerrarSessionRequest();
    }

    /**
     * Create an instance of {@link AutentificarResponse }
     * 
     */
    public AutentificarResponse createAutentificarResponse() {
        return new AutentificarResponse();
    }

    /**
     * Create an instance of {@link AutentificarWebResponse }
     * 
     */
    public AutentificarWebResponse createAutentificarWebResponse() {
        return new AutentificarWebResponse();
    }

    /**
     * Create an instance of {@link AutorizarRequest }
     * 
     */
    public AutorizarRequest createAutorizarRequest() {
        return new AutorizarRequest();
    }

    /**
     * Create an instance of {@link AutorizarResponse }
     * 
     */
    public AutorizarResponse createAutorizarResponse() {
        return new AutorizarResponse();
    }

    /**
     * Create an instance of {@link CerrarSessionWebResponse }
     * 
     */
    public CerrarSessionWebResponse createCerrarSessionWebResponse() {
        return new CerrarSessionWebResponse();
    }

    /**
     * Create an instance of {@link CerrarSessionWebRequest }
     * 
     */
    public CerrarSessionWebRequest createCerrarSessionWebRequest() {
        return new CerrarSessionWebRequest();
    }

    /**
     * Create an instance of {@link AutorizarWebRequest }
     * 
     */
    public AutorizarWebRequest createAutorizarWebRequest() {
        return new AutorizarWebRequest();
    }

    /**
     * Create an instance of {@link AutorizarWebResponse }
     * 
     */
    public AutorizarWebResponse createAutorizarWebResponse() {
        return new AutorizarWebResponse();
    }

}
