//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.09.26 at 10:35:55 AM CDT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://com/blog/samples/webservices/seguridadservice", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.blog.samples.webservices.seguridadservice;
